#!/usr/bin/env bash

set -Eeo pipefail

CONTENT_DIR=content/blog

function check_hugo {
    if ! command -v hugo >/dev/null; then
        echo "Hugo not found, exiting..."
        exit 1
    fi
}

function check_git {
    if ! command -v git >/dev/null; then
        echo "Git not found, exiting..."
        exit 1
    fi
}

function server {
    check_hugo

    echo "Starting Hugo server..."
    hugo server --buildDrafts $@
}

function draft {
    check_hugo

    echo "Creating new draft $@"
    hugo new blog/$@
}

function undraft {
    check_hugo

    echo "Undrafting $CONTENT_DIR/$@..."
    hugo undraft $CONTENT_DIR/$@
    mv $CONTENT_DIR/$@ $CONTENT_DIR/$(date +"%F")-$@
    echo "Undraft complete..."
}

# publish command from the hugo website
function publish {
    check_hugo
    check_git

    echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"
    # Build the project.
    hugo
    # Go To Public folder
    cd public
    # Add changes to git.
    git add .
    # Commit changes.
    msg="Rebuilding site $(date)"
    if [ $# -eq 1 ]; then
        msg="$1"
    fi
    git commit -m "$msg"
    # Push source and build repos.
    git push origin master
    # Come Back up to the Project Root
    cd ..
}

case "$1" in
  server)
    server $2
    ;;

  draft)
    draft $2
    ;;

  undraft)
    undraft $2
    ;;

  publish)
    publish $2
    ;;
  *)
    echo $"Usage: $0 {server|draft <draft-name>.md|undraft <draft-name>.md|publish commit-message}"
    exit 1
esac
