#!/usr/bin/env bash

set -Eeo pipefail

CONTENT_DIR=content/blog

function check_hugo {
    if ! command -v hugo >/dev/null; then
        echo "Hugo not found, exiting..."
        exit 1
    fi
}

function check_git {
    if ! command -v git >/dev/null; then
        echo "Git not found, exiting..."
        exit 1
    fi
}

function server {
    check_hugo

    echo "Starting Hugo server..."
    hugo server --buildDrafts $@
}

function draft {
    check_hugo

    echo "Creating new draft $@"
    hugo new --kind blog ${CONTENT_DIR}/$@
}

function undraft {
    check_hugo

    local new_filename=${CONTENT_DIR}/$(date +"%F")-$@

    echo "Undrafting ${CONTENT_DIR}/$@..."
    mv ${CONTENT_DIR}/$@ $new_filename
    sed -i '' "/draft: true/d" $new_filename
    echo "Undraft complete..."
}

case "$1" in
  server)
    server $2
    ;;

  draft)
    draft $2
    ;;

  undraft)
    undraft $2
    ;;
  *)
    echo $"Usage: $0 {server|draft <draft-name>.md|undraft <draft-name>.md}"
    exit 1
esac
