baseURL: https://albertogrespan.com
disablePathToLower: true
languageCode: en-us
title: Blog

author:
  name: Alberto Grespan
  email: alberto@albertogrespan.com

params:
  author: Alberto Grespan
  domain: albertogrespan.com
  gravatar:
    url: https://www.gravatar.com/avatar/006ef14fba8fadd40053ecda5039deb2.png
    title: albertogg
  connect:
    email: alberto@albertogrespan.com
    feed: https://albertogrespan.com/feed.atom
    twitter:
      url: https://twitter.com/albertogg
      handle: albertogg
    github:
      url: https://github.com/albertogg
      handle: albertogg

# Taxonomies activation
taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
